[package]
name = "dioxus_learning"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.0-alpha.1", features = ["desktop", "web", "router"] }
dioxus-desktop = "0.7.0-alpha.1"
dioxus-router = "0.7.0-alpha.1"
